cache:
  pip: true
jobs:
  include:
    - language: python
      python: 3.7
      env: TOXENV=flake8
    - language: python
      python: 3.7
      env: TOXENV=mypy
    - language: python
      python: 3.7
      env: TOXENV=py37
install:
  - pip install --upgrade pip
  - pip install codecov tox
script:
  - tox
after_success:
  codecov
